Updated lesson 09
Alliedium/devops-course-2022 pull request #64
Opened 2022-12-14 13:14 UTC by tzatushevskaya

2022-12-21 20:52 UTC, irublev requested changes

2022-12-21 20:52 UTC, irublev commented on 09_proxmox_fstrim_cloudinit_ansible_lvm_08-sep-2022/fstrim_timer.md
>  LVM thin pools instead allocates blocks when they are written.
allocate -> allocates

2022-12-21 20:52 UTC, irublev commented on 09_proxmox_fstrim_cloudinit_ansible_lvm_08-sep-2022/fstrim_timer.md
>  -   Enable `Discard` and `SSD Emulation` flags for drive
could you please attach a screenshot (or make a reference to another lesson with this screenshot)?

2022-12-21 20:52 UTC, irublev commented on 09_proxmox_fstrim_cloudinit_ansible_lvm_08-sep-2022/fstrim_timer.md
>  -   Regularly run `fstrim` inside guest OS (doesn't matter hdd or ssd used on the host machine)
doesn't matter **whether** hdd or ssd **is** used on the host machine

2022-12-21 20:52 UTC, irublev commented on 09_proxmox_fstrim_cloudinit_ansible_lvm_08-sep-2022/cloudinit-exp/cloudinit.md
>  nano ./create-rocky9-dc0.sh
please avoid using _I_ or _my_ at all.

I have this script I've passed from another vm via scp, it is placed here -> This script passed from another VM via scp, it is placed here:

(please change vm to VM and vms to VMs throughout the files).

2022-12-21 20:52 UTC, irublev commented on 09_proxmox_fstrim_cloudinit_ansible_lvm_08-sep-2022/cloudinit-exp/cloudinit.md
>  You have to edit parameters accordingly to your preferences and settings on your machine.
Please also avoid using you:

It is necessary to edit parameters accordingly to the desired preferences and settings on the machine.

2022-12-21 20:52 UTC, irublev commented on 09_proxmox_fstrim_cloudinit_ansible_lvm_08-sep-2022/cloudinit-exp/cloudinit.md
> +Then you run the script (or commands from it one by one):
Then you run the script -> Then the script is to be run

2022-12-21 20:52 UTC, irublev commented on 09_proxmox_fstrim_cloudinit_ansible_lvm_08-sep-2022/ansible/ansible.md
>  1. We should have ansible installed on the vm we want to execute the ansible playbook on.
vm -> VM

2022-12-21 20:52 UTC, irublev commented on 09_proxmox_fstrim_cloudinit_ansible_lvm_08-sep-2022/ansible/ansible.md
>  nano ./playbooks/change-hostnames.yml
We should also have **a** script created / placed in the following directory

2022-12-21 20:52 UTC, irublev commented on 09_proxmox_fstrim_cloudinit_ansible_lvm_08-sep-2022/ansible/ansible.md
>  We need hosts.ini file to specify the ip addresses of the hosts we want to change by this script.
ip -> IP, ips -> IPs

2022-12-21 20:52 UTC, irublev commented on 09_proxmox_fstrim_cloudinit_ansible_lvm_08-sep-2022/ansible/ansible.md
>  Once we have specified the ips and the hostnames we would like to be set on those vms,
vms -> VMs

2022-12-21 20:52 UTC, irublev commented on 09_proxmox_fstrim_cloudinit_ansible_lvm_08-sep-2022/ansible/ansible.md
>  ```
Should appear in the list: -> The role should appear in the list:

2022-12-21 20:52 UTC, irublev commented on 09_proxmox_fstrim_cloudinit_ansible_lvm_08-sep-2022/lvm_resize_additional_pv.md
>  1. Attach the new storage to the system.
the new storage -> a new storage

2022-12-21 20:52 UTC, irublev commented on 09_proxmox_fstrim_cloudinit_ansible_lvm_08-sep-2022/simple-https/systemctl.md
>  ```
why do you need this [tatyana@rocky ~]$ below?

2022-12-21 20:52 UTC, irublev commented on 09_proxmox_fstrim_cloudinit_ansible_lvm_08-sep-2022/simple-https/systemctl.md
>  1. We need 3 files in simple-https directory (you can find them in simple-https directory and pass via scp onto your VM):
could you please point the exact commands (possibly starting from cloning this Git repo)?

2023-01-26 16:13 UTC, bbs-md commented on 09_proxmox_fstrim_cloudinit_ansible_lvm_08-sep-2022/simple-https/README.md
> +
All commnds were executed on `Manajaro` Linux distribution

2023-01-30 14:16 UTC, merged