Updated lesson 22
Alliedium/devops-course-2022 pull request #65
Opened 2022-12-15 12:46 UTC by tzatushevskaya

2022-12-21 21:15 UTC, irublev requested changes

2022-12-21 21:15 UTC, irublev commented on 22_networks_vlan_opnsense_vms_25-oct-2022/README.md
> +* Install SDN
where to do this? it is clear only for those who already know the answer

2022-12-21 21:15 UTC, irublev commented on 22_networks_vlan_opnsense_vms_25-oct-2022/README.md
> +* Update hostname & ip address:
where to do this?

2022-12-21 21:15 UTC, irublev commented on 22_networks_vlan_opnsense_vms_25-oct-2022/README.md
> +* Re-generate certificates
and this?

2022-12-21 21:15 UTC, irublev commented on 22_networks_vlan_opnsense_vms_25-oct-2022/README.md
> +* Send ssh key to each node
how to do this?

2022-12-21 21:15 UTC, irublev commented on 22_networks_vlan_opnsense_vms_25-oct-2022/README.md
> +* Run script to create ubuntu cloudinit template on 1st node
which script?

2022-12-21 21:15 UTC, irublev commented on 22_networks_vlan_opnsense_vms_25-oct-2022/README.md
> +- Check IP address:
where to do this?

2023-01-25 15:32 UTC, bbs-md commented on 22_networks_vlan_opnsense_vms_25-oct-2022/README.md
> +  - Firewall > Rules: close web to LAN (enable the rule LAN to LAN only)
- Firewall > Rules -> LAN
 web access

2023-01-25 15:33 UTC, bbs-md commented on 22_networks_vlan_opnsense_vms_25-oct-2022/README.md
> +  - Firewall > Live Log > filter by interface LAN
- Firewall > Log Files > Live View

2023-01-25 15:35 UTC, bbs-md commented on 22_networks_vlan_opnsense_vms_25-oct-2022/README.md
> +      - parent ens18
ens18.3

2023-01-25 15:35 UTC, bbs-md commented on 22_networks_vlan_opnsense_vms_25-oct-2022/README.md
> +  - Firewall > Live Log > filter by interface
Firewall > Log Files > Live View

2023-01-25 15:36 UTC, bbs-md commented on 22_networks_vlan_opnsense_vms_25-oct-2022/README.md
> +    - parent ens18
ens18.3

2023-01-25 15:38 UTC, bbs-md commented on 22_networks_vlan_opnsense_vms_25-oct-2022/README.md
> +- Set up network connection via _nmtui_
In `manjaro3` VM terminal

2023-01-26 11:14 UTC, merged